# Usar una imagen de Python como base
FROM python:3.12

# Crear directorio de trabajo
WORKDIR /server

# Copiar archivos de la aplicación
COPY . .

# Instalar dependencias
RUN pip install -r requirements.txt

# Exponer el puerto 5000
EXPOSE 5000

RUN pip install gunicorn

# Ejecutar el servidor Flask con Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
